### ISSUE TITLE
Multiple fixes available on original VADER (python code by cjchutto) but not ported to PHP

### ISSUE THREAD

**Issue by PeterH220** [abusby/php-vadersentiment#6]

**Comment by lennox02** [comment]
Anyone who ends up here - this is a much more modern port of vader for php (it just doesn't have vader in the repo name)

https://github.com/davmixcool/php-sentiment-analyzer

**Comment by PeterH220** [comment]
> Anyone who ends up here - this is a much more modern port of vader for php (it just doesn't have vader in the repo name)
> 
> https://github.com/davmixcool/php-sentiment-analyzer

Same sh*t. I ended up making my own port, expanded and much more accurate.
